### ISSUE TITLE
Request::getContentType Does Not Exist

### ISSUE THREAD

**Issue by anthonykusuma** [mtownsend5512/request-xml#12]
- Laravel 11

Hi, after upgrading Laravel to version 11 and `request-xml` to the latest version(2.4.0), I got this error when I ran a test that passed on Laravel 10.

```bash
[2024-03-28 07:38:25] testing.ERROR: Method Illuminate\Http\Request::getContentType does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method Illuminate\\Http\\Request::getContentType does not exist. at ~/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:112)
[stacktrace]
#0 ~/vendor/mtownsend/request-xml/src/Providers/RequestXmlServiceProvider.php(56): Illuminate\\Http\\Request->__call('getContentType', Array)
#1 ~/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(123): Illuminate\\Http\\Request->Mtownsend\\RequestXml\\Providers\\{closure}()
#2 ~/vendor/mtownsend/request-xml/src/Providers/RequestXmlServiceProvider.php(68): Illuminate\\Http\\Request->__call('isXml', Array)
#3 ~/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php(123): Illuminate\\Http\\Request->Mtownsend\\RequestXml\\Providers\\{closure}()
#4 ~/vendor/mtownsend/request-xml/src/Middleware/XmlRequest.php(18): Illuminate\\Http\\Request->__call('xml', Array)
#5 ~/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Mtownsend\\RequestXml\\Middleware\\XmlRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
```

can you please show me how to debug this? Thank you.

**Comment by joeljohn135** [comment]
Check for the updated version of **mtownsend/request-xml.** Check the documentation for updates.

**Comment by anthonykusuma** [comment]
Thanks @joeljohn135 

It seems to be trying to call`getContentType()` method that does not exist in Laravel's request object.

https://github.com/mtownsend5512/request-xml/blob/46f63f20d3c36599975b57d88fd8088175f1ef81/src/Providers/RequestXmlServiceProvider.php#L56
